### ISSUE TITLE
Physical cartridge clarification

### ISSUE THREAD

**Issue by Knatan** [Shinigati/LoHUndubVita#2]
I felt a little left out and confused when reading your guide since it was likely written for digital copy, and the problem is I have physical cartridge.
I tried to read through your guide from step 1 to 2 to 3, and at no point was it clear to me just when I should have the cartridge inserted to my Vita.

So I also have a few questions.
Will it be alright if I insert the cartridge and install the game icon and keep the cartridge inside the Vita for the remainder of the guide before follow your step 1?
Will it be alright if I updated my game to version 1.02 before I follow your step 1? Or must I stay at version 1.00 of the game?

**Comment by Shinigati** [comment]
I don't understand how clear it needs to be to say when you need the game inserted that goes without saying when you start dumping your game or if you're using the pre-patched file you don't actually need it inserted at all but i've already wrote up how to do it for the physical version when dumping data.psarc
As for updated there is no way to get them working with the undub because the new eboot.bin file from it tells the game exactly what files to read and simply ignored data.psarc i've been trying to decrypt the contents so i can possibly merge them into data.psarc but so far i've had no luck this is why i said to rename ux0:patch/TITLEID first if there is one there already so you can just restore it later without deleting your game because the vita will still think the game is up to date.

**Comment by Knatan** [comment]
Thanks for the clarification.
